import nodemailer from 'nodemailer';

// Email configuration from environment variables
const smtpHost = process.env.SMTP_HOST || 'mail.davikithtours.com';
const smtpPort = parseInt(process.env.SMTP_PORT || '587');
const smtpUser = process.env.SMTP_USER || 'info@davikithtours.com';
const smtpPass = process.env.SMTP_PASS || 'Davikith2026!';
const smtpSecure = process.env.SMTP_SECURE === 'true'; // false for port 587, true for port 465
const notificationReceiver = process.env.NOTIFICATION_RECEIVER || 'Davikithtours@gmail.com';

// Create a transporter only if SMTP config exists
let transporter: nodemailer.Transporter | null = null;

function getTransporter() {
  if (!transporter) {
    if (!smtpUser || !smtpPass) {
      console.warn('⚠️ SMTP email credentials not configured. Emails will not be sent.');
      return null;
    }

    transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpSecure,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
      tls: {
        // Do not fail on invalid certs (common for shared hosting local self-signed certs)
        rejectUnauthorized: false,
      },
    });
  }
  return transporter;
}

export interface ContactNotificationData {
  name: string;
  email: string;
  phone?: string;
  subject?: string;
  message: string;
  inquiry_type: string;
  preferred_contact: string;
  newsletter: boolean;
}

export interface BookingNotificationData {
  tour_name?: string;
  customer_name: string;
  customer_email: string;
  customer_phone?: string;
  start_date: string;
  end_date: string;
  guests: number;
  total_amount: number;
  special_requests?: string;
}

/**
 * Sends a notification email for a new contact form submission
 */
export async function sendContactNotification(data: ContactNotificationData): Promise<boolean> {
  const mailClient = getTransporter();
  if (!mailClient) return false;

  const subject = `[New Contact Inquiry] - ${data.subject || 'General Inquiry'}`;
  
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
      <div style="background-color: #2c3e50; padding: 20px; text-align: center; color: white;">
        <h2 style="margin: 0; font-size: 24px;">New Website Contact Inquiry</h2>
      </div>
      <div style="padding: 20px;">
        <p style="font-size: 16px;">You have received a new inquiry from the contact form on Davikiths Tours website. Details are below:</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; width: 180px;">Name:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.name}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Email:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><a href="mailto:${data.email}">${data.email}</a></td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Phone:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.phone || 'N/A'}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Inquiry Type:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; text-transform: capitalize;">${data.inquiry_type}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Preferred Contact:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; text-transform: capitalize;">${data.preferred_contact}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Newsletter Opt-In:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.newsletter ? 'Yes' : 'No'}</td>
          </tr>
        </table>
        
        <div style="margin-top: 20px; background-color: #f9f9f9; padding: 15px; border-left: 4px solid #3498db; border-radius: 4px;">
          <h4 style="margin: 0 0 10px 0;">Message:</h4>
          <p style="margin: 0; white-space: pre-wrap;">${data.message}</p>
        </div>
      </div>
      <div style="background-color: #f5f5f5; padding: 15px; text-align: center; font-size: 12px; color: #777; border-top: 1px solid #eee;">
        This email was automatically generated by the Davikiths Tours server.
      </div>
    </div>
  `;

  try {
    const info = await mailClient.sendMail({
      from: `"${data.name} via Davikiths Tours" <${smtpUser}>`,
      to: notificationReceiver,
      replyTo: data.email,
      subject: subject,
      html: htmlContent,
    });
    console.log('📬 Contact email notification sent successfully:', info.messageId);
    return true;
  } catch (error) {
    console.error('❌ Failed to send contact notification email:', error);
    return false;
  }
}

/**
 * Sends a notification email for a new tour booking
 */
export async function sendBookingNotification(data: BookingNotificationData): Promise<boolean> {
  const mailClient = getTransporter();
  if (!mailClient) return false;

  const subject = `[New Tour Booking] - ${data.tour_name || 'Safari Booking'}`;
  
  // Format currency
  const formattedAmount = data.total_amount 
    ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(data.total_amount)
    : 'Pending invoice';

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
      <div style="background-color: #27ae60; padding: 20px; text-align: center; color: white;">
        <h2 style="margin: 0; font-size: 24px;">New Booking Reservation!</h2>
      </div>
      <div style="padding: 20px;">
        <p style="font-size: 16px;">Congratulations! A new tour booking has been placed on the website. Reservation details are as follows:</p>
        
        <h3 style="color: #27ae60; border-bottom: 2px solid #27ae60; padding-bottom: 5px; margin-top: 20px;">Customer Info</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; width: 180px;">Customer Name:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.customer_name}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Customer Email:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><a href="mailto:${data.customer_email}">${data.customer_email}</a></td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Customer Phone:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.customer_phone || 'N/A'}</td>
          </tr>
        </table>

        <h3 style="color: #27ae60; border-bottom: 2px solid #27ae60; padding-bottom: 5px; margin-top: 20px;">Booking Details</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; width: 180px;">Tour / Package Name:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">${data.tour_name || 'N/A'}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Start Date:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.start_date}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">End Date:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.end_date}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Guests:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${data.guests}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Total Paid / Quoted:</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold; color: #27ae60;">${formattedAmount}</td>
          </tr>
        </table>
        
        ${data.special_requests ? `
        <div style="margin-top: 20px; background-color: #f9f9f9; padding: 15px; border-left: 4px solid #27ae60; border-radius: 4px;">
          <h4 style="margin: 0 0 10px 0;">Special Requests:</h4>
          <p style="margin: 0; white-space: pre-wrap;">${data.special_requests}</p>
        </div>
        ` : ''}
      </div>
      <div style="background-color: #f5f5f5; padding: 15px; text-align: center; font-size: 12px; color: #777; border-top: 1px solid #eee;">
        This email was automatically generated by the Davikiths Tours server.
      </div>
    </div>
  `;

  try {
    const info = await mailClient.sendMail({
      from: `"Davikiths Tours Bookings" <${smtpUser}>`,
      to: notificationReceiver,
      replyTo: data.customer_email,
      subject: subject,
      html: htmlContent,
    });
    console.log('📬 Booking email notification sent successfully:', info.messageId);
    return true;
  } catch (error) {
    console.error('❌ Failed to send booking notification email:', error);
    return false;
  }
}
